### PR TITLE
WIP: Prettier autoformat (js, css, md)

### PR DESCRIPTION
**Pull request by manics**
Opening this to illustrate how [**prettier**](https://prettier.io/) works.

Note it's picked up some CSS syntax errors:
```
omeroweb/webclient/static/webclient/css/layout.css
[error] omeroweb/webclient/static/webclient/css/layout.css: SyntaxError: (postcss) CssSyntaxError Unknown word (314:31)
[error]   312 |
[error]   313 |
[error] > 314 |                 #left_panel_tab_list li a:hover, #annotation_tabs_list li a:hover;{
[error]       |                                      ^
[error]   315 |                     text-decoration: none;
[error]   316 |                     background:rgba(255,255,255,.1);
[error]   317 |                                 color:white;
omeroweb/webadmin/static/webadmin/css/chosen.css
[error] omeroweb/webadmin/static/webadmin/css/chosen.css: SyntaxError: (postcss) CssSyntaxError Missed semicolon (7:93)
[error]    5 |   text-shadow:0 1px 0 rgba(255,255,255,.4);
[error]    6 |   background: #E3646F; /* Old browsers */
[error] >  7 |   background: -moz-linear-gradient(center top , #E3646F 0%, #E3646F 100%) repeat scroll 0 0 #FFFFFF
[error]      |                                                                                             ^
[error]    8 |   background-color:hsl(210,30%,70%);
[error]    9 |   filter:progid:DXImageTransform.Microsoft.gradient( startColorstr='#E3646F', endColorstr='#E3646F',GradientType=0 ); /* IE6-9 */
[error]   10 |   background:linear-gradient(top, hsl(210,40%,70%) 0%,hsl(210,40%,60%) 100%); /* W3C */
omeroweb/webgateway/static/webgateway/css/omero_image.css
[error] omeroweb/webgateway/static/webgateway/css/omero_image.css: SyntaxError: (postcss) CssSyntaxError Missed semicolon (256:11)
[error]   254 |   position: relative;
[error]   255 |   width: 100%;
[error] > 256 |   height: 100%
[error]       |           ^
[error]   257 |   overflow: hidden;
[error]   258 | }
[error]   259 |
```

--exclude

@will-moore

### CODE REVIEW

**Comment by manics** [comment]
Before fixing those syntax errors we'll need to check what effect it has. Is a missing semicolon handled gracefully by browsers, or is the style ignored? How is the first error (semicolon before the brace) handled? `#left_panel_tab_list li a:hover, #annotation_tabs_list li a:hover;{`.

**Comment by will-moore** [comment]
Thanks for looking into this.
I'd really like to get https://github.com/ome/omero-web/pull/180 merged first, because manually fixing conflicts between that and this would be a bit painful.

**Comment by manics** [comment]
No rush, I thought I'd open this just so everyone can see what it does, in case they want to apply it to other repos.

**Comment by joshmoore** [comment]
Re-opening to trigger another newly added workflow:

https://github.com/ome/omero-web/commit/4b88d6adf10bcbd2916f34cd346c08ed29a9b824

**Comment by joshmoore** [comment]
Hmmm.... it didn't trigger on the PR but it ran on master with no warnings: https://github.com/ome/omero-web/actions/runs/281772511

**Pull request closed without merging**
