### PR TITLE
Use pkg_resources to locate nginx templates

### PR DESCRIPTION
**Pull request by manics**
`omero web config nginx` should now work

Removes 4 of the xfails from https://github.com/ome/omero-web/issues/18, 2 remain

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#52](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/52/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/52/consoleText) for more details.
Possible conflicts:
  - PR #15 will-moore 'Py3 fixes'
    - omero/plugins/web.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#53](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/53/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/53/consoleText) for more details.
Possible conflicts:
  - PR #15 will-moore 'Py3 fixes'
    - omero/plugins/web.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#54](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/54/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/54/consoleText) for more details.
Possible conflicts:
  - PR #15 will-moore 'Py3 fixes'
    - omero/plugins/web.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#55](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/55/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/55/consoleText) for more details.
Possible conflicts:
  - PR #15 will-moore 'Py3 fixes'
    - omero/plugins/web.py

--conflicts

**Comment by joshmoore** [comment]
> 2 remain

What's the reasoning?

**Comment by joshmoore** [comment]
Otherwise, unit tests are green, and applying this change to a running OMERO.web works locally. :+1: Propose to merge and update @will-moore's PR.

**Comment by manics** [comment]
The remaining xfails are `testWebRestart` and `testWebBadRestart`, unrelated to this fix.

**Comment by joshmoore** [comment]
Cheers.

**Pull request merged**
