### PR TITLE
Fix Tag creation in webclient

### PR DESCRIPTION
**Pull request by will-moore**
Fix bug reported at:
https://docs.google.com/spreadsheets/d/1ry6vS0dmsylFQDAiIZDrPC3kXNpnHSMtK-2yj5X8jaU/edit#gid=420881033

"Add Tag fails if tag is new: Click on the plus button in Tags harmonice in RHP and try to create a new tag. This fails after clicking "Save" with no error displayed (just a blank form "Send feedback" appears). The addition of tags works if these tags are created previously via the Tags tab."

### CODE REVIEW

**Comment by joshmoore** [comment]
py3 (40) passes tag creation. merge (224) RHP is not loading:
Screen Shot 2019-11-05 at 09 02 00

**Comment by will-moore** [comment]
Can't reproduce locally - merge-ci is running Django 1.11, right?

**Comment by joshmoore** [comment]
I don't imagine it's possible to run anything _but_ Django 1.11 at the moment.

**Comment by joshmoore** [comment]
Manually tested merge this morning and it's now also working. Leaving the gh-56 PR for discussion of the RHP. Only remaining question is if there should have been a test for this? (Or would it be included in the robot tests?)

**Comment by will-moore** [comment]
Yes, good point. I'll try and add a test ASAP

**Comment by joshmoore** [comment]
Merging based on merge-ci (233) and py3-ci (52)

**Pull request merged**
