### PR TITLE
imgData JSON with no stateful services

### PR DESCRIPTION
**Pull request by will-moore**
It has been noted in some cases that the Preview panel and the right panel of iviewer can take a long time to load, since we currently initialise various stateful services (which requires initialising them with the original image files). This means that the viewers are slower to load than if we just get the data from the DB, particularly if access to original data is slow.

Stateful services usage is replaced as follows:

 - Instead of using rendering engine for settings, we load rendering def
 - Instead of the rawPixelsStore for `image.getPixelRange()`, we lookup values based on pixel type
 - Instead of using rendering engine for `requiresPixelsPyramid()` we use `image.requiresPixelsPyramid()` which simply uses the size cut-off.
 - IF the image is BIG, *then* we load the rendering engine to get the actual pyramid resolutions

To test:
 - Image viewer should work as before but load faster
 - The only other change in behaviour is for small images that have a pyramid, such as small NGFF images. These will appear as small images in the Preview panel and will load as whole planes instead of tiles in iviewer.
 - Instead of using `re.lookupRenderingDef(pid, ctx)` for the logic of "use my rdef or use the owners", this is now encoded in `webgateway.util.get_rendering_def()`
 - If no rendering def exists, we use rendering engine to create one as before.

Also see performance testing with NGFF data on idr-testing at https://github.com/ome/omero-web/pull/537#issuecomment-2004001921
Summarised as follows:
 - Don't expect this PR to noticeably improve performance for *most* data in OMERO
 - For data where we do notice a significant improvement (e.g. idr0090 NGFF data) even if we always use RenderingEngine to test/load the pyramid levels (ie. NO api change), this PR still has a performance improvement.

### CODE REVIEW

**Comment by will-moore** [comment]
Deploy on idr-testing...
```
for server in omeroreadwrite omeroreadonly-1 omeroreadonly-2 omeroreadonly-3 omeroreadonly-4; do ssh $server "sudo /opt/omero/web/venv3/bin/pip uninstall -y omero-web && sudo /opt/omero/web/venv3/bin/pip install git+https://github.com/ome/omero-web.git@refs/pull/536/head && sudo service omero-web restart"; done
```
This failed since it's still python 3.6 and this branch (based on latest omero-web) requires Django 4.2!
Reverted...
```
for server in omeroreadwrite omeroreadonly-1 omeroreadonly-2 omeroreadonly-3 omeroreadonly-4; do ssh $server "sudo /opt/omero/web/venv3/bin/pip install omero-web && sudo service omero-web restart"; done
```

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#468](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/468/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/468/consoleText) for more details.
Possible conflicts:
  - PR #531 knabar 'Removal of python-future compatibility code '
    - omeroweb/webgateway/marshal.py
    - omeroweb/webgateway/util.py
  - PR #534 will-moore 'get strings from omero.cmd.ERR and omero.CmdError correctly'
    - omeroweb/webgateway/marshal.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#12](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/12/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/12/consoleText) for more details.
Possible conflicts:
  - PR #531 knabar 'Removal of python-future compatibility code '
    - omeroweb/webgateway/marshal.py
    - omeroweb/webgateway/util.py
  - PR #534 will-moore 'get strings from omero.cmd.ERR and omero.CmdError correctly'
    - omeroweb/webgateway/marshal.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#470](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/470/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/470/consoleText) for more details.
Possible conflicts:
  - PR #531 knabar 'Removal of python-future compatibility code '
    - omeroweb/webgateway/marshal.py
    - omeroweb/webgateway/util.py
  - PR #534 will-moore 'get strings from omero.cmd.ERR and omero.CmdError correctly'
    - omeroweb/webgateway/marshal.py

--conflicts

**Comment by will-moore** [comment]
Deployed on idr-testing from branch at #537, this is returning different `zoomLevelScaling` from previously!?
On https://idr.openmicroscopy.org/webclient/img_detail/9840218/ that image has:

```
    "tiles": true,
    "tile_size": {
        "width": 240,
        "height": 240
    },
    "levels": 3,
    "zoomLevelScaling": {
        "0": 1.0,
        "1": 0.2499840367792606,
        "2": 0.029308473277568484
    },
```

But on idr-testing, a different zoomLevelScaling is causing problems:

Screenshot 2024-02-28 at 13 40 52

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#13](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/13/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/13/consoleText) for more details.
Possible conflicts:
  - PR #531 knabar 'Removal of python-future compatibility code '
    - omeroweb/webgateway/marshal.py
    - omeroweb/webgateway/util.py
  - PR #534 will-moore 'get strings from omero.cmd.ERR and omero.CmdError correctly'
    - omeroweb/webgateway/marshal.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#471](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/471/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/471/consoleText) for more details.
Possible conflicts:
  - PR #531 knabar 'Removal of python-future compatibility code '
    - omeroweb/webgateway/util.py
    - omeroweb/webgateway/marshal.py
  - PR #534 will-moore 'get strings from omero.cmd.ERR and omero.CmdError correctly'
    - omeroweb/webgateway/marshal.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#14](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/14/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/14/consoleText) for more details.
Possible conflicts:
  - PR #531 knabar 'Removal of python-future compatibility code '
    - omeroweb/webgateway/marshal.py
    - omeroweb/webgateway/util.py
  - PR #534 will-moore 'get strings from omero.cmd.ERR and omero.CmdError correctly'
    - omeroweb/webgateway/marshal.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#472](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/472/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/472/consoleText) for more details.
Possible conflicts:
  - PR #531 knabar 'Removal of python-future compatibility code '
    - omeroweb/webgateway/marshal.py
    - omeroweb/webgateway/util.py
  - PR #534 will-moore 'get strings from omero.cmd.ERR and omero.CmdError correctly'
    - omeroweb/webgateway/marshal.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#473](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/473/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/473/consoleText) for more details.
Possible conflicts:
  - PR #534 will-moore 'get strings from omero.cmd.ERR and omero.CmdError correctly'
    - omeroweb/webgateway/marshal.py
  - Upstream changes
    - omeroweb/webgateway/util.py
    - omeroweb/webgateway/marshal.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#16](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/16/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/16/consoleText) for more details.
Possible conflicts:
  - PR #534 will-moore 'get strings from omero.cmd.ERR and omero.CmdError correctly'
    - omeroweb/webgateway/marshal.py
  - Upstream changes
    - omeroweb/webgateway/util.py
    - omeroweb/webgateway/marshal.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#474](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/474/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/474/consoleText) for more details.
Possible conflicts:
  - PR #534 will-moore 'get strings from omero.cmd.ERR and omero.CmdError correctly'
    - omeroweb/webgateway/marshal.py
  - Upstream changes
    - omeroweb/webgateway/marshal.py
    - omeroweb/webgateway/util.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#17](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/17/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/17/consoleText) for more details.
Possible conflicts:
  - PR #534 will-moore 'get strings from omero.cmd.ERR and omero.CmdError correctly'
    - omeroweb/webgateway/marshal.py
  - Upstream changes
    - omeroweb/webgateway/util.py
    - omeroweb/webgateway/marshal.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#475](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/475/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/475/consoleText) for more details.
Possible conflicts:
  - PR #534 will-moore 'get strings from omero.cmd.ERR and omero.CmdError correctly'
    - omeroweb/webgateway/marshal.py
  - Upstream changes
    - omeroweb/webgateway/marshal.py
    - omeroweb/webgateway/util.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#18](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/18/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/18/consoleText) for more details.
Possible conflicts:
  - PR #534 will-moore 'get strings from omero.cmd.ERR and omero.CmdError correctly'
    - omeroweb/webgateway/marshal.py
  - Upstream changes
    - omeroweb/webgateway/marshal.py
    - omeroweb/webgateway/util.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#476](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/476/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/476/consoleText) for more details.
Possible conflicts:
  - PR #534 will-moore 'get strings from omero.cmd.ERR and omero.CmdError correctly'
    - omeroweb/webgateway/marshal.py
  - Upstream changes
    - omeroweb/webgateway/marshal.py
    - omeroweb/webgateway/util.py

--conflicts

**Comment by knabar** [comment]
There are still some concerns about this potentially introducing breaking API changes.  

Are issues like https://github.com/ome/omero-web/pull/536#issuecomment-1969020266 still happening?

Performance improvements seem to be limited to particular image types (https://github.com/ome/omero-web/pull/537#issuecomment-2004001921).

The way image pyramids/tiles are detected changes the behavior of the API endpoint.

* Could this be introduced as a new API endpoint instead, for individual clients to use once it's verified that there are no issues with that particular client?
* Or alternatively, add a query argument like `?skipRenderingEngine` without which the previous behavior remains exactly?

Both those options would guarantee that no clients break in an unexpected fashion with any images, and clients that might benefit could be updated to use the new behavior with a single line change to the new endpoint or by adding the query argument.

**Comment by will-moore** [comment]
Sorry - please ignore https://github.com/ome/omero-web/pull/536#issuecomment-1969020266 - I just happened to find that bug when testing this PR so I reported it here, but it's not related to this PR.

I'll revert the API changes as suggested (always use renderingEngine to check for pyramids), then we can discuss if it's worth adding a `skipRenderingEngine` option...

**Comment by will-moore** [comment]
@knabar I replaced much of the code in the same order as before, so the PR changes are reduced.
One change in the last commit is to not return early if the rendering engine fails to load, since we can maybe still add other useful info, particularly if we can load rendering defs.

**Comment by knabar** [comment]
I set up a temporary branch that exposes both the original and the new `imgData` endpoint at https://github.com/knabar/omero-web/tree/temp-try-imgdata-json

Using the following commands on `bash` to compare the outputs, I tried a number of different images:
```bash
ID=347168
COOKIE='Cookie: csrftoken=...; sessionid=...'
diff <(curl -s http://localhost:4080/webgateway/imgDataOriginal/${ID}/ -H ${COOKIE} | jq --sort-keys .) \
  <(curl -s http://localhost:4080/webgateway/imgData/${ID}/ -H ${COOKIE} | jq --sort-keys .)
```

So far the main difference is with the channels `min`/`max` being returned as integers instead of floats, but more unusual images still need to be tested.

```
14,15c14,15
<         "max": 65535.0,
<         "min": 0.0,
---
>         "max": 65535,
>         "min": 0,
30,31c30,31
<         "max": 65535.0,
<         "min": 0.0,
---
>         "max": 65535,
>         "min": 0,
46,47c46,47
<         "max": 65535.0,
<         "min": 0.0,
---
>         "max": 65535,
>         "min": 0,
```

cc: @sbesson

**Comment by will-moore** [comment]
Re: https://github.com/ome/omero-web/pull/536#issuecomment-2013257938 float vv ints:
Testing with floating-point images (with #548 deployed on idr-testing) I see that the window values are also floats:
https://idr-testing.openmicroscopy.org/webclient/imgData/1884808/

```
"window": {
  "min": -2147483648,
  "max": 7880.49462890625,
  "start": 2509.07969,
  "end": 5488.61182
}
```

**Comment by will-moore** [comment]
Since it appears we don't now need these changes for IDR, closing....

**Pull request closed without merging**
