### PR TITLE
Create release

### PR DESCRIPTION
**Pull request by jburel**
This PR adds an action that will create a release when a tag is pushed
This will allow to check for upgrade in QA.

### CODE REVIEW

**Comment by jburel** [comment]
The "hit" endpoint checks if an upgrade is required. This only works for OMERO.server
I have adjusted the code so it also works for omero-web, insight
For that I checked what is the latest value available from  GitHub using ``https://github.com/ome/omero-web/releases/latest``

**Comment by sbesson** [comment]
Thanks, you might be able to use the REST API directly as in https://api.github.com/repos/ome/omero-web/releases/latest

I'll leave @knabar to evaluate as he's going to be primarily involved here but I am not convinced that adding yet another GitHub workflow is justified here. Instead we could just update the release process and manually create a release after pushing the tag, this takes a few clicks and <30s using the current UI. Another potential caveat of the automated workflow is that we might not necessarily want to create GitHub releases for every tag and notably for release candidates if this API is going to be consumed by the OME upgrade check logic.

**Comment by jburel** [comment]
openmicroscopy and insight create a release. 
That's why I picked that approach so I had the same piece of code to find the information
but if we don't want to create a release I will have to modify the code again i.e.
```
    r = requests.get(url)
    ver = regex.match(r.url).group(1)
```

**Comment by jburel** [comment]
I have now modified the code to use the REST API i.e. https://api.github.com/repos/ome/omero-web/tags
I will delete the release that I created manually

**Pull request closed without merging**
