### PR TITLE
fix test_metadata

### PR DESCRIPTION
**Pull request by will-moore**
Fixes https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/34/testReport/OmeroWeb.test.integration.test_metadata/TestCoreMetadata/test_none_pixel_size/

### CODE REVIEW

**Comment by joshmoore** [comment]
https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/37/testReport/OmeroWeb.test.integration.test_metadata/TestCoreMetadata/test_none_pixel_size/ is failing with:

```
>       assert "no_pixels" in rsp.content
E       TypeError: a bytes-like object is required, not 'str'

test/integration/test_metadata.py:89: TypeError
```

(merge build 222 looks fine)

**Comment by jburel** [comment]
Fixed in https://github.com/ome/openmicroscopy/pull/6161

**Comment by jburel** [comment]
https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/38/testReport/OmeroWeb.test.integration.test_metadata/TestCoreMetadata/test_none_pixel_size/ fixed

**Comment by joshmoore** [comment]
Test still passing on merge (224) and py3 (40)

**Pull request merged**
