### PR TITLE
fix api test_container_crud

### PR DESCRIPTION
**Pull request by will-moore**
Fixes https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/31/testReport/OmeroWeb.test.integration.test_api_containers/TestContainers/test_container_crud_Project_/

Needs omero-marshal fix too...

### CODE REVIEW

**Comment by joshmoore** [comment]
> Needs omero-marshal fix too...

Shall we get https://github.com/ome/omero-marshal/pull/65 tagged then?

**Comment by will-moore** [comment]
I think I recently saw another test that was failing with omero-marshal unicode handling. Just can't find it now...

**Comment by will-moore** [comment]
Yes, lets tag https://github.com/ome/omero-marshal/pull/65

**Comment by joshmoore** [comment]
merge 228 and py3 46 are both green. marshal 0.6.3 was released and bumped.

**Pull request merged**
