### PR TITLE
Mark unused templates as deprecated

### PR DESCRIPTION
**Pull request by will-moore**
This PR deletes a bunch of old templates used for the old home page which showed a tag cloud and recent imports.

Not used in a LONG time. Also duplicates a lot of code. Good to clean up.

### CODE REVIEW

**Comment by jburel** [comment]
We do not use those templates. Technically speaking, someone might have adjusted the webclient and may still be using it.
I think we should follow the same pattern as we do for the code. Mark the template as ``deprecated`` for this release, and remove them the next one.

**Review by jburel — CHANGES_REQUESTED** [review]
We do no longer use those templates. Technically speaking, someone might have adjusted the webclient and may still be using it.
I think we should follow the same pattern as we do for the code. Mark the template as ``deprecated`` for this release, and remove them the next one.

**Comment by will-moore** [comment]
I can't find an official way of marking Django templates as deprecated, but I could add some appropriate comments to the templates.
I guess I could add a `<script>` with something like:

```
console.warn("OMERO.web template at webclient/base/base.html is deprecated")
```

or even use `alert("OMERO.web template at webclient/base/base.html is deprecated")` to be *really* sure that it gets seen?

**Review by jburel — APPROVED** [review]
Thanks @will-moore for making the adjustments

**Comment by jburel** [comment]
Is the last commit expected on this PR?

**Comment by will-moore** [comment]
@jburel Thanks - This is the last PR for 5.17.0 so I updated the Changelog accordingly in this PR.
If it looks good, please go ahead and merge when ready - Thanks

**Comment by sbesson** [comment]
Have you guys also evaluated https://github.com/ome/omero-web/pull/431 which could be a possible candidate for 5.17.0?

I assume the goal is to cut a release asap to start the testing of #433?

**Comment by jburel** [comment]
@sbesson including https://github.com/ome/omero-web/pull/431 in the release makes sense
As discussed in previous meeting, the aim is to have a release before the upgrade work so we have a reference point.
@will-moore: Could you create a PR with the changelog entry only so it is clearer to review and add #431?

**Pull request merged**
