### PR TITLE
Script delete

### PR DESCRIPTION
**Pull request by will-moore**
NB: This is on top of #126.
Adds support for deleting scripts from webclient.

Screenshot 2020-02-19 at 13 33 21

To test:
 - Login as Admin
 - Choose Delete option
 - Try deleting 1 or more scripts
 - On completion, they should be removed from the webclient scripts menu.

### CODE REVIEW

**Comment by jburel** [comment]
Click on delete script
```
Traceback (most recent call last):

  File "/home/omero/workspace/OMERO-web/.venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)

  File "/home/omero/workspace/OMERO-web/.venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)

  File "/home/omero/workspace/OMERO-web/.venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/omero/workspace/OMERO-web/.venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 485, in wrapped
    retval = f(request, *args, **kwargs)

  File "/home/omero/workspace/OMERO-web/.venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 555, in wrapper
    return render(request, template, context)

  File "/home/omero/workspace/OMERO-web/.venv3/lib64/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)

  File "/home/omero/workspace/OMERO-web/.venv3/lib64/python3.6/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)

  File "/home/omero/workspace/OMERO-web/.venv3/lib64/python3.6/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)

django.template.exceptions.TemplateDoesNotExist: webclient/scripts/delete_script.html

<WSGIRequest: GET '/web/webclient/script_delete/'>
```

**Comment by will-moore** [comment]
Sorry - I missed the html template from my commit above. Fixed now.

**Comment by jburel** [comment]
* The list of the scripts should be displayed in a scrollpane.
* Select a script and try to delete. Error
delete_script

**Comment by jburel** [comment]
I was able to delete the newly uploaded script
but not "official" script

**Comment by will-moore** [comment]
@jburel - I don't know why you can delete some scripts and not others. I could delete several "Official" scripts but not others. I see errors when deleting via CLI too:

```
Failed to delete script: 395701 (exception ::omero::ValidationException
...
 serverExceptionClass = ome.conditions.ValidationException
    message = could not delete: [ome.model.core.OriginalFile#395701]; SQL [delete from originalfile where id=?]; constraint [fkjoboriginalfilelink_child_originalfile]; nested exception is org.hibernate.exception.ConstraintViolationException: could not delete: [ome.model.core.OriginalFile#395701]
```
Although after that, the script no-longer shows up in ```omero script list``` or in web UI.

I updated web to improve display of the error:

Screenshot 2020-02-24 at 17 12 52

**Comment by jburel** [comment]
It could be that the script has been run. This will require further investigation

**Comment by jburel** [comment]
* Uploaded figure script.
* Run it
* I can still delete it

Even if an exception is returned, the file is no longer returned in a follow-up call.
This is far too flaky to be exposed in the UI

**Comment by will-moore** [comment]
Closing for now till other issues resolved

**Pull request closed without merging**
