### PR TITLE
paths to object ROI

### PR DESCRIPTION
**Pull request by will-moore**
Required for iviewer https://github.com/ome/omero-iviewer/pull/311

To test:
 - Test added at https://github.com/ome/openmicroscopy/pull/6228
 - Find an ROI ID and go to ```/webclient/api/paths_to_object/?roi=1```
 - Should see JSON path to the ROI:
 - See empty list if ROI ID is not found
```
{
    "paths": [
        [
            {
                "type": "experimenter",
                "id": 2
            },
            {
                "type": "project",
                "id": 152
            },
            {
                "type": "dataset",
                "id": 151,
                "childCount": 33
            },
            {
                "type": "image",
                "id": 838
            },
            {
                "type": "roi",
                "id": 179711
            }
        ]
    ]
}
```

### CODE REVIEW

**Comment by joshmoore** [comment]
That means this should likely bump the omero-web minor version as an API addition, no?

**Comment by will-moore** [comment]
Yes, bump omero-web version so that omero-iviewer can depend on it.

If chown or api_experimenters_groups PRs are in the next omero-web, they will also depend on a new version of omero-py.

**Comment by jburel** [comment]
Tested the following:
* https://merge-ci.openmicroscopy.org/web/webclient/api/paths_to_object/?image=1132
```
{"paths": [[{"type": "experimenter", "id": 452}, {"type": "dataset", "id": 1051, "childCount": 7}, {"type": "image", "id": 1132}]]}
```
*  https://merge-ci.openmicroscopy.org/web/webclient/api/paths_to_object/?project=5757
```
{"paths": [[{"type": "experimenter", "id": 452}, {"type": "project", "id": 5757}]]}
```
* https://merge-ci.openmicroscopy.org/web/webclient/api/paths_to_object/?dataset=5170
```
{"paths": [[{"type": "experimenter", "id": 452}, {"type": "project", "id": 1757}, {"type": "dataset", "id": 5170}], [{"type": "experimenter", "id": 452}, {"type": "project", "id": 5757}, {"type": "dataset", "id": 5170}]]}
```
* https://merge-ci.openmicroscopy.org/web/webclient/api/paths_to_object/?screen=1654
```
{"paths": [[{"type": "experimenter", "id": 452}, {"type": "screen", "id": 1654}]]}
```
* https://merge-ci.openmicroscopy.org/web/webclient/api/paths_to_object/?plate=2506
```
{"paths": [[{"type": "experimenter", "id": 452}, {"type": "screen", "id": 1654}, {"type": "plate", "id": 2506}], [{"type": "experimenter", "id": 452}, {"type": "screen", "id": 2505}, {"type": "plate", "id": 2506}]]}
```
* https://merge-ci.openmicroscopy.org/web/webclient/api/paths_to_object/?roi=26762
```
{"paths": [[{"type": "experimenter", "id": 452}, {"type": "dataset", "id": 1051, "childCount": 7}, {"type": "image", "id": 1132}, {"type": "roi", "id": 26762}]]}
```

The fact that the ROI's ID is in the tooltip implies that it is not as easy to find the ID as it is for other object

**Comment by will-moore** [comment]
@jburel So this is good to merge?
Tests at https://github.com/ome/openmicroscopy/pull/6228 are still passing, so that is good to merge too?

**Comment by jburel** [comment]
@will-moore yes. The usability for finding ROI's ID will have to be reviewed but this is outside the scope of this PR

**Pull request merged**
