### PR TITLE
use conda-forge channel

### PR DESCRIPTION
**Pull request by jburel**
Corresponding PR ~https://github.com/ome/omero-py/pull/397~
https://github.com/ome/omero-py/pull/407

### CODE REVIEW

**Comment by knabar** [comment]
@will-moore @jburel Reviewing PRs for inclusion into the next OMERO.web release - is this one something to include?

**Comment by jburel** [comment]
I need to adjust something here

**Comment by jburel** [comment]
Adjusted see https://github.com/ome/omero-py/pull/407

**Comment by jburel** [comment]
@knabar changes pushed

**Pull request merged**
