### PR TITLE
Make 'remove all filters' properly clear map filters.

### LINKED ISSUE #348: Key-Value filters are not cleared by the 'remove all filters' option
In the center panel, the 'Add Filter' dropdown allows the user to create different filter types to restrict which images are displayed.

That dropdown includes a 'Remove all filters' option which clears any filters that the user has set.

However, while running this option removes Key-Value filters from the display, those filters are still applied. I don't think you can remove them without refreshing the page. Removing map filters individually still works.

This problem appears to be exclusive to Key-Value filters, other filter types are removed successfully.

### PR DESCRIPTION
**Pull request by DavidStirling**
Fixes #348

I believe that the problem with the 'remove all filters' option was that it didn't wipe the Key-Value filters list. Adding code to do this (if any filters are present) seems to fix the issue.

### CODE REVIEW

**Comment by joshmoore** [comment]
Launched the workflows for testing. @DavidStirling : do you happen to see an invite to the org?

**Comment by DavidStirling** [comment]
Unfortunately I'm not seeing an invite, sorry!

**Comment by joshmoore** [comment]
No worries. Resent.

**Comment by DavidStirling** [comment]
Got it, thanks!

**Comment by will-moore** [comment]
Thanks for that. Tested locally. Looks good.

**Pull request merged**
