### PR TITLE
Fix new flake8 warnings

### PR DESCRIPTION
**Pull request by joshmoore**
Especially "E741 ambiguous variable name".
see: https://github.com/ome/openmicroscopy/pull/6236

### CODE REVIEW

**Comment by joshmoore** [comment]
cc: @manics @will-moore 

This is needed to get https://github.com/ome/omero-web/pull/168 passing

**Comment by will-moore** [comment]
Looks good 👍

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#334](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/334/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/334/consoleText) for more details.
Possible conflicts:
  - PR #148 will-moore 'api_experimenters_groups'
    - omeroweb/webclient/webclient_gateway.py
  - PR #154 will-moore 'public user workflow crash'
    - omeroweb/webclient/webclient_gateway.py

--conflicts

**Comment by will-moore** [comment]
@joshmoore conflict with #148 

I can close that if you just want to get this in? Then rebase etc.

**Comment by joshmoore** [comment]
Thanks. I went ahead and added `--exclude` to the description of #148. I'll re-run the build and see how things are this evening.

**Comment by joshmoore** [comment]
Re-run https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/415/ passed with 9 _seemingly_ unrelated failures. Merging to unblock #148 and we can re-address as necessary.

**Pull request merged**
