### PR TITLE
Django 1.9

### PR DESCRIPTION
**Pull request by will-moore**
Although our Django update strategy hasn't been discussed fully, I started looking at it by upgrading from Django 1.8 to 1.9.

At this point I can log into webclient etc.
Next: fix lots of Deprecation warnings and more testing....

### CODE REVIEW

**Comment by joshmoore** [comment]
Excluding due to:

```
TypeError: __init__() got an unexpected keyword argument 'builtins'
```

--exclude

**Comment by will-moore** [comment]
It looks like the stack trace might be Django 1.8 (some line numbers don't match the 1.9 code), but don't know where that might be specified, since this PR updates the version in ```omero-web/requirements-py27.txt``` and the CLI should show an error for version ```<1.9```

<summary>
<details>

```
[2019-09-03 16:36:22 +0000] [42603] [ERROR] Error handling request /web/webclient/login/?url=%2Fweb%2Fwebclient%2F
Traceback (most recent call last):
  File "/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 268, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/home/omero/workspace/OMERO-web/OMERO.web/lib/python/omeroweb/feedback/views.py", line 188, in handler500
    t = template_loader.get_template('500-nosubmit.html')
  File "/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python2.7/site-packages/django/template/loader.py", line 29, in get_template
    engines = _engine_list(using)
  File "/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python2.7/site-packages/django/template/loader.py", line 143, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python2.7/site-packages/django/template/utils.py", line 110, in all
    return [self[alias] for alias in self]
  File "/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python2.7/site-packages/django/template/utils.py", line 101, in __getitem__
    engine = engine_cls(params)
  File "/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python2.7/site-packages/django/template/backends/django.py", line 24, in __init__
    self.engine = Engine(self.dirs, self.app_dirs, **options)
TypeError: __init__() got an unexpected keyword argument 'builtins'
```
</details>
</summary>

**Comment by joshmoore** [comment]
Likely requires a review (and linked PRs) of other repositories, especially devspace, omero-install, and openmicroscopy.

**Comment by joshmoore** [comment]
@will-moore : note a few conflicts here as well as the `--exclude` will need to be addressed if this is the next best step on the Django front.

**Comment by will-moore** [comment]
@joshmoore Where are you seeing ```TypeError: __init__() got an unexpected keyword argument 'builtins'```?
I merged ```master``` branch to fix conflicts.
Does this still need to be excluded?

**Comment by will-moore** [comment]
Travis failing with ```ERROR:: You need Python 3.4 or greater to install PyTables!```.

**Comment by joshmoore** [comment]
Apologies, @will-moore. I forgot to remove `--exclude` in the current run. Now done. We can either re-run now, or wait for tomorrow AM.

**Comment by will-moore** [comment]
Ah, yes - I just saw that https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/195/consoleFull had:
```
Collecting Django<1.9,>=1.8 (from -r /home/omero/workspace/OMERO-test-integration/src/dist/share/web/requirements-py27.txt (line 8))
```

**Comment by will-moore** [comment]
Lots of failures at https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/196/ due to Django 1.8 being installed.
I see that Django 1.8 is also specified in https://github.com/ome/openmicroscopy/blob/develop/components/tools/OmeroWeb/requirements-py27.txt (which is copied into /home/omero/workspace/OMERO-test-integration/src/dist/share/web/requirements-py27.txt by https://github.com/ome/openmicroscopy/blob/develop/build.xml#L384

So, need to update there too...

**Comment by joshmoore** [comment]
After manual testing yesterday (inspired by a nearly green round of integration tests), the Django 1.9 state with at least the iviewer and parade plugins looks good. Merging and tagging as `5.6.dev2` so Django 1.11 work can proceed.

**Pull request merged**
