### PR TITLE
Update jquery

### PR DESCRIPTION
**Pull request by will-moore**
Started following jQuery upgrade guide:
https://jquery.com/upgrade-guide/3.0/

Completed running of all robot tests (see https://github.com/ome/openmicroscopy/pull/6291) against merge-ci branch (containing this branch) and only 1 minor bug found, fixed in ed7f2f0 below.

### CODE REVIEW

**Comment by joshmoore** [comment]
cc: @bramalingam in case there's any conflict here.

**Comment by will-moore** [comment]
Need to check whether jQuery-UI slider issues in omero-figure are caused by this PR: https://github.com/ome/omero-figure/issues/397

**Comment by will-moore** [comment]
Seems jquery-UI dialog close button is not placing "Close" text inside the 2nd span (as it did before). Instead the "Close" text is it's own node:
```
<button type="button" class="ui-button ui-corner-all ui-widget ui-button-icon-only ui-dialog-titlebar-close" title="Close">. 
    <span class="ui-button-icon ui-icon ui-icon-closethick"></span>
    <span class="ui-button-icon-space"> </span>
    "Close"
</button>
```
which mean it's not hidden by `text-indent: -9999999px`.

Screenshot 2020-08-07 at 13 47 50

So, need to hide with 'color':'transparent' on the button

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#406](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/406/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/406/consoleText) for more details.
Failed to autodetect conflicts

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#412](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/412/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/412/consoleText) for more details.
Failed to autodetect conflicts

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#419](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/419/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/419/consoleText) for more details.
Failed to autodetect conflicts

--conflicts

**Comment by will-moore** [comment]
It would be good to get this in to the next `omero-web` release. cc @sbesson 
It has been in the merge build for a while, but I'll list for testing...

**Comment by sbesson** [comment]
Depending on how long it takes to get this tested, I would be fine for this to get included in a minor release of omero-web.

As it stands, #238, #240, #232 #245 are already merged but unrelased. In addition to this PR, #243 is also a candidate for merging now the examples have been added. Anything else you can think of?
I would be in favor of drawing a line under the roadmap of `omero-web 5.9.0` as we might need to come back to the Django upgrade early in 2021 which will probably push us towards `omero-web 6.0.0`

**Comment by will-moore** [comment]
I would like to get #225 in too. It doesn't fix all bugs when adding/removing annotations using 500 images, but it does fix the original one found on IDR: #223

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#577](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/577/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/577/consoleText) for more details.
Failed to autodetect conflicts

--conflicts

**Comment by will-moore** [comment]
In order to test https://github.com/ome/omero-figure/pull/417 independently of this PR, excluding...

--exclude

**Comment by will-moore** [comment]
NB: also need to update OMERO.parade and decide what other essential apps to test/update.

Also need to warn in docs and image.sc etc, *before* release? (deprecation warning)?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#603](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/603/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/603/consoleText) for more details.
Failed to autodetect conflicts

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#614](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/614/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/614/consoleText) for more details.
Failed to autodetect conflicts

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#618](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/618/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/618/consoleText) for more details.
Failed to autodetect conflicts

--conflicts

**Comment by will-moore** [comment]
Looked at OMERO.parade and confirmed that it doesn't use any jQuery code in the main app (It's all React.js code).

**Comment by joshmoore** [comment]
As mentioned during standup, if this could affect downstream users, I'd be for getting it into a minor release RC and then post something on image.sc asking for help in testing.

@Carsten Fortmann-Grote and his work with OMERO.forms might be one candidate.

**Comment by will-moore** [comment]
Last commit fixes auto-complete menu used by `mapr`:
Before:
Screenshot 2021-09-01 at 13 17 11

After:
Screenshot 2021-09-01 at 13 18 12

**Comment by will-moore** [comment]
Fixed a couple of bugs due to `$.on("hover", fn, fn)` being removed in jQuery 1.9 (see https://api.jquery.com/on/).
Dropdown menus (user profile menu and toolbar menus in right panel) and the roi thumbnail in old viewer.

**Comment by pwalczysko** [comment]
Issue: Copy and Paste of Link. 

Description:
merge-ci: 
1. Log in as user-3.  Either read-only-1 or read-annotate-1 groups tested, the behaviour is identical in both.
2. Have at least 2 Projects and within them at least 1 Dataset each.
3. Remember the situation prior to the action and also visualize the expected result (ie. for example intending to copy the first Dataset from the first Project into the second Project)
4. Select the first Dataset in the first Project, right-click and click Edit > Copy
5. Select the second Project, right-click and click Edit > Paste
6. Observe that the target Project vanished from display
7. Observe that the copy of the Dataset is also not displayed
8. Use the refresh button above the LHP (inside OMERO.web)
9. Observe that the second (target) Project is back on display, but 
10. Observe that the action (copying of the P-D link) was not performed, ie. the Dataset is not shown under the second Project as expected

The above scenario works fine on latest-ci. Even without clicking the Refresh button, the copied Dataset is immediately displayed as expected.

**Comment by pwalczysko** [comment]
Bug: Move All does not display

Description
merge-ci:

1. Find a MIF, for example https://merge-ci.openmicroscopy.org/web/webclient/?show=image-169215
2. Select only one image of the fileset, then right-click Move to Group
3. Observe that the first dialog gives you the message about the need to move the whole MIF, but
4. Also observe that in the bottom right corner the "Move All" option is not given, instead
5. In the bottom right corner is an "OK" button, which does not elicit any action when clicked

merge-ci

Screenshot 2021-09-06 at 17 15 27


outreach (without this PR)
Screenshot 2021-09-06 at 17 15 40

**Comment by pwalczysko** [comment]
The old testing sheet https://docs.google.com/spreadsheets/d/10Go_WZNBm84vR9MqxQd6CHQhxmwq-B9XR5-Xh-fgCU4/edit#gid=469737557 proved very useful for detecting both above problems.
Went through the items, mainly Copy, Render, Create, Move, Delete and checking links. Except for as reported above https://github.com/ome/omero-web/pull/180#issuecomment-913688888 and https://github.com/ome/omero-web/pull/180#issuecomment-913758106 all worked. As for the permissions, I did only 2-3 ad-hoc setups (working in RO and RA groups on Render, Copy, Delete on yours or others data, as member, owner or admin).

Maybe we can have one more look at the sheet if there is something worth going deeper into.

**Comment by will-moore** [comment]
Thanks @pwalczysko - First commit above fixes the Copy & Paste bug for me locally.
Unfortunately I don't understand what caused it or how to check for possibly related bugs.
Also fixed the chgrp "Move All".

**Comment by pwalczysko** [comment]
Both problems https://github.com/ome/omero-web/pull/180#issuecomment-913688888 and https://github.com/ome/omero-web/pull/180#issuecomment-913758106 are fixed now on merge-ci

**Comment by pwalczysko** [comment]
Went again through https://docs.google.com/spreadsheets/d/10Go_WZNBm84vR9MqxQd6CHQhxmwq-B9XR5-Xh-fgCU4/edit#gid=469737557, doing in all group types the Copy + Paste workflow on Datasets and Images as member, owner, admin. All worked.
Also tested creation of a Plate using the script and its display, and Rendering setting (RA and RO groups only). Also did some Moves of data, RA and RO groups only.
Tested also creation of new P/D/S.

All seems okay, fmpov I would be happy to go ahead here.

**Comment by pwalczysko** [comment]
Bug (found by @will-moore , I can confirm):

1. go to webadmin and click the ``Create New User`` button
2. Select the Administrator as the radio button option but do not click Save
3. Observe that system group was added to the list of groups where the new user is a member of
4. Select the User as the radio button option
5. Observe that the system group was not removed from the list of groups
6. Click Save (whilst on the radio option "User")
7. Observe that the new user is an Admin, not a User

Also tried some other workflows, including creation and downgrading of new group and the Stats panel.
This worked fine.

**Comment by pwalczysko** [comment]
Bug? History tab:

1. Log in as user-6 to merge-ci
2. Go to History tab
3. find 1st of September and click on it
4. This day contains a Dataset called "2000...." as seen in the central pane listing
5. Observe that there is no Dataset icon shown on the 1st September though,  the only way to know that the Dataset "2000..." is present on 1st September was to click on that day blindly
6. Compare with outreach, where the days have the icons in them. 
7. Nevertheless, observe that the outreach server (release OMERO.web) does not display anything in the central pane when the days with icons are clicked
8. Not sure what the correct behaviour is, both seem insufficient :)

merge-ci (1st September clicked)

Screenshot 2021-09-09 at 18 13 47

outreach (release OMERO.web, 6th of August clicked)
Screenshot 2021-09-09 at 18 15 13

**Comment by jburel** [comment]
Discussed today. Merging and creating an rc

**Pull request merged**
