### PR TITLE
Pad the bottom of jstree

### PR DESCRIPTION
**Pull request by manics**
Closes https://github.com/ome/omero-web/issues/234, see issue for testing instructions.

### CODE REVIEW

**Comment by will-moore** [comment]
Testing locally, that appears to pad the bottom of every jsTree node:

Screenshot 2020-10-13 at 08 38 55

**Comment by will-moore** [comment]
Try

```
.left_panel_tree {
   height: calc(100% - 20px);
}
```
instead of `height: 100%`, seems to do the trick, but it doesn't look very nice.

Screenshot 2020-10-13 at 08 48 10

**Comment by manics** [comment]
Oops, not sure how that happened.... maybe my browser cached something....
```
.jstree-container-ul {
  padding-bottom: 2em;
}
```
seems looks OK in Firefox
image

**Comment by will-moore** [comment]
The nicer solution might be to remove the `href='#'` on each `<a>` node in jsTree.
There seems to be a few people requesting this. See links from
https://github.com/vakata/jstree/issues/1655

**Comment by jburel** [comment]
@will-moore will you take over?

**Comment by jburel** [comment]
Closing 
replaced by https://github.com/ome/omero-web/pull/257

**Pull request closed without merging**
