### PR TITLE
Jstree padding bottom

### PR DESCRIPTION
**Pull request by will-moore**
This replaces https://github.com/ome/omero-web/pull/237

EDIT: Instead of padding under the tree, we now use a `<span>` element instead of `<a>` for the jstree nodes, as discussed at https://github.com/vakata/jstree/pull/1616

The tree should look and behave the same, but nodes are no-longer links so we don't get the link popup when we mouse over.

### CODE REVIEW

**Comment by jburel** [comment]
I can see the difference between merge and release version.
Small improvement, maybe other users could be used to make the benefit of the change more obvious
Screenshot 2021-02-15 at 12 20 29
Screenshot 2021-02-15 at 12 20 49

**Comment by jburel** [comment]
Discussed with @will-moore closing

**Comment by joshmoore** [comment]
What was discussed? Wouldn't some improvement be better than none? (I regularly lose the last new IDR study in the UI)

**Comment by will-moore** [comment]
This PR currently makes the UI look a bit broken:
It's not really clear where the bottom of the panel is or why that space is not being used or why items disappear before the bottom of the page. So as it stands that change generally makes the UI worse.

Screenshot 2021-02-16 at 08 47 50

So, it needs something else:
 - Put something else in that gap (different colour and blank, or some other placeholder)?
 - Fix jsTree so that it doesn't have ```<a>``` tags - some discussion of people doing this (see links from previous PR) but haven't looked at how much work or other issues with this.

We felt that this wasn't worth the time to fix a relatively minor issue.

**Comment by will-moore** [comment]
NB: I think IDR is a slightly odd use-case where we are almost always most interested in the last item of the tree. But for most users, that is the "Orphaned Images" and so might not be so bad.
The fact that this issue has arisen "internally" and not as feedback from users was also a factor in the discussion.

**Comment by joshmoore** [comment]
Is there an option to have this fix then at least when orphaned images is turned off.  cf. https://github.com/ome/omero-web/issues/234#issuecomment-704181932 For the IDR use case, this is quite significant. (But I do wonder if there are users who don't know there's an orphaned images folder hidden at the bottom)

**Comment by jburel** [comment]
Padding was an option but when it is applied "blindly" is not great for the general case, it certainly improves the IDR case.
Since it was a change in the css, having the conf coming from the server will probably be tricky to apply so alternative needs to be looked into (jsTree as @will-moore mentioned for example)

**Comment by joshmoore** [comment]
Happy to leave you guys to recommend a solution that either is IDR-only or works across the board. But currently we have three closed items (#257, #237, #234) and nothing on the radar for a fix.

**Comment by jburel** [comment]
I will re-open so it is included in the build and people can look at it further and discuss option

**Comment by jburel** [comment]
* url obstruction the view has now been removed. That url was not clickable/copiable.
* Cut/paste: count updated without refresh
* D&D: count updated without refresh
* Bug: I cannot D&D an image from a dataset into an empty dataset. This works on outreach
* Bug: I cannot D&D a dataset (empty or not) into a project. This works on outreach

**Comment by jburel** [comment]
I have not noticed any problems with the tree
but it will be good to have a second pair of eyes
@pwalczysko could you have a look at it?

**Comment by pwalczysko** [comment]
> I have not noticed any problems with the tree
> but it will be good to have a second pair of eyes
> @pwalczysko could you have a look at it?

Tested the whole right-click context menu in the LHP tree, checked the image/dataset counters, tried drag and drop, and also all the icons above the LHP.

All worked as expected. Ready to merge fmpov.

**Comment by jburel** [comment]
Thanks @pwalczysko

**Pull request merged**
