### PR TITLE
Split view figure big images

### LINKED ISSUE #391: SplitView figure script fails with big images
From e-mail today: Page at `https://demo.openmicroscopy.org/webclient/figure_script/SplitView/?Image=235413`
requested a Big Image plane with https://demo.openmicroscopy.org/webclient/render_image/235413/?c=3&m=c
which fails with:
```
    serverExceptionClass = ome.conditions.ApiUsageException
    message = 109560×92138 plane too large, cannot exceed 2^31 pixels
```

This UI for creating figures is deprecated (replaced by OMERO.figure) so instead of adding support for big images, just need to check for big image and say "not supported".

### PR DESCRIPTION
**Pull request by will-moore**
Fixes #391 

To test:

 - Select 1 or more images, including a Big image
 - Run Split_View_Figure script
 - Big Image won't be included in the UI and a warning is shown:

Screenshot 2022-10-05 at 11 01 25

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#1211](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/1211/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/1211/consoleText) for more details.
Possible conflicts:
  - PR #17 will-moore 'Right panel performance fixes'
    - omeroweb/webclient/views.py
  - PR #225 will-moore 'Query string ids'
    - omeroweb/webclient/views.py
  - PR #399 will-moore 'Handle chgrp dry-run LogicalChannel[ID] to show images'
    - omeroweb/webclient/views.py
  - PR #410 will-moore 'Allow multiple file-annotations to be uploaded'
    - omeroweb/webclient/views.py

--conflicts

**Comment by jburel** [comment]
@will-moore This PR could also be considered but first other PRs will need to be excluded due to the conflict so it can be tested

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#114](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/114/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/114/consoleText) for more details.
Possible conflicts:
  - PR #17 will-moore 'Right panel performance fixes'
    - omeroweb/webclient/views.py
  - PR #225 will-moore 'Query string ids'
    - omeroweb/webclient/views.py
  - Upstream changes
    - omeroweb/webclient/views.py

--conflicts

**Comment by jburel** [comment]
* Select a big image only
* The image is correctly not added to the UI
* Warning message is displayed
* I can still click on the button to create a figure. This should be disabled

**Comment by will-moore** [comment]
@jburel That last commit should disable the Submit if there are no images

**Comment by jburel** [comment]
The Submit button is now disabled.
There is still a problem:
* Select 2 images, one is a big image
* Only one in the UI: expected
* Error message in info
* ```WARNING:omero.gateway:ApiUsageException on <class 'omero.gateway.OmeroGatewaySafeCallWrapper'> to <e803b8ec-7da9-4ab0-b018-20db0f645c62omero.api.RenderingEngine> renderCompressed((object #0 (::omero::romio::PlaneDef)
{
    slice = 0
    x = 0
    y = 0
    z = 0
    t = 0
    region = <nil>
    stride = 0
},), {})
Traceback (most recent call last):
  File "/home/omero/workspace/OMERO-server/.venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 4863, in __call__
    return self.f(*args, **kwargs)
  File "/home/omero/workspace/OMERO-server/.venv3/lib64/python3.6/site-packages/omero_api_RenderingEngine_ice.py", line 913, in renderCompressed
    return _M_omero.api.RenderingEngine._op_renderCompressed.invoke(self, ((_def, ), _ctx))
omero.ApiUsageException: exception ::omero::ApiUsageException
{
    serverStackTrace = ome.conditions.ApiUsageException: 62425Ã—60101 plane too large, cannot exceed 2^31 pixels
	at omeis.providers.re.RGBIntBuffer.<init>(RGBIntBuffer.java:63)
	at omeis.providers.re.RenderingStrategy.getIntBuffer(RenderingStrategy.java:186)
	at omeis.providers.re.HSBStrategy.renderAsPackedInt(HSBStrategy.java:291)
	at omeis.providers.re.Renderer.renderAsPackedInt(Renderer.java:558)
	at ome.services.RenderingBean.renderAsPackedInt(RenderingBean.java:512)
	at ome.services.RenderingBean.renderCompressed(RenderingBean.java:542)
	at sun.reflect.GeneratedMethodAccessor2173.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
```
indicates that the big image is still pass to the server.

Since this PR still requires some work, we should not hold back on the dependencies upgrade work and include this PR in a later version and release asap

**Comment by jburel** [comment]
This time:
* Selected 2 images (not big). Both images are in the UI. The figure is created with the 2 images and attached to the first one
* Selected 2 images: one big. Only the "small" image is in the UI. The figure is created with 1 image and attached to the image
* Select one big image only:

```
 File "/home/omero/workspace/OMERO-web/.venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)

  File "/home/omero/workspace/OMERO-web/.venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/omero/workspace/OMERO-web/.venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 544, in wrapped
    retval = f(request, *args, **kwargs)

  File "/home/omero/workspace/OMERO-web/.venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 603, in wrapper
    context = f(request, *args, **kwargs)

  File "/home/omero/workspace/OMERO-web/.venv3/lib64/python3.6/site-packages/omeroweb/webclient/views.py", line 4271, in figure_script
    image = validImages[imageIds[0]]

IndexError: list index out of range

<WSGIRequest: GET '/web/webclient/figure_script/SplitView/?Image=105665'>
```

**Comment by jburel** [comment]
Excluding ahead of the dependencies upgrade work

--exclude

**Comment by jburel** [comment]
I have removed ``exclude`` label. This will be included in the build

**Comment by will-moore** [comment]
Since the Split-View Figure is broken now (see https://github.com/ome/omero-web/pull/443#issuecomment-1434696762) and might be removed, this PR is on-hold till that is resolved

**Comment by will-moore** [comment]
The issues with https://github.com/ome/omero-web/pull/443#issuecomment-1434696762 are now resolved, so this is ready for another test.

**Comment by will-moore** [comment]
Saw from demo today - coming from Split-View figure...
```
Internal Server Error: /webclient/render_image/249148/

ApiUsageException at /webclient/render_image/249148/
exception ::omero::ApiUsageException
{
    serverStackTrace = ome.conditions.ApiUsageException: 81672×37589 plane too large, cannot exceed 2^31 pixels
```

**Comment by will-moore** [comment]
Ready for a "final" test... I'll list in standup...

**Comment by pwalczysko** [comment]
Tested all the workflows mentioned above by @jburel - lgtm

**Review by pwalczysko — APPROVED** [review]

**Pull request merged**
