### PR TITLE
unit tests

### PR DESCRIPTION
**Pull request by will-moore**
This is on top of @joshmoore's ```remove integration tests``` branch.

Work in progress.
At current state, we have

```
$ python -m pytest
=================================================================================================== test session starts ===================================================================================================
platform darwin -- Python 2.7.16, pytest-4.6.5, py-1.8.0, pluggy-0.12.0
rootdir: /Users/willadmin/Desktop/WEB/omero-web
collected 91 items                                                                                                                                                                                                        

test/unit/test_marshal.py .............                                                                                                                                                                             [ 14%]
test/unit/test_render_response.py FFFFFFFFFFFFF                                                                                                                                                                     [ 28%]
test/unit/test_settings.py ...                                                                                                                                                                                      [ 31%]
test/unit/test_show.py ...................                                                                                                                                                                          [ 52%]
test/unit/test_tree.py .........                                                                                                                                                                                    [ 62%]
test/unit/test_util.py ..FFFFFF............                                                                                                                                                                         [ 84%]
test/unit/test_webgateway.py ...........F..   
```

### CODE REVIEW

**Comment by will-moore** [comment]
Failing to import ```webgateway``` but I can't work out where this is coming from.

```
$ python -m pytest test/unit/test_render_response.py -k test_load_settings_defaults
=================================================================================================== test session starts ===================================================================================================
platform darwin -- Python 2.7.16, pytest-4.6.5, py-1.8.0, pluggy-0.12.0
rootdir: /Users/willadmin/Desktop/WEB/omero-web
collected 13 items / 12 deselected / 1 selected                                                                                                                                                                           

test/unit/test_render_response.py F                                                                                                                                                                                 [100%]

======================================================================================================== FAILURES =========================================================================================================
_____________________________________________________________________________________ TestRenderResponse.test_load_settings_defaults ______________________________________________________________________________________

args = (<test_render_response.TestRenderResponse object at 0x111932c50>,), kwargs = {}

    @wraps(test_func)
    def inner(*args, **kwargs):
        with self:
>           return test_func(*args, **kwargs)

../../../Virtual/omero/lib/python2.7/site-packages/django/test/utils.py:196: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/unit/test_render_response.py:51: in test_load_settings_defaults
    context = call_load_settings(self.r, None)
test/unit/test_render_response.py:39: in call_load_settings
    render_response().load_settings(request, context, conn)
omeroweb/webclient/decorators.py:183: in load_settings
    l["link"] = reverse(link_id)
../../../Virtual/omero/lib/python2.7/site-packages/django/core/urlresolvers.py:578: in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
../../../Virtual/omero/lib/python2.7/site-packages/django/core/urlresolvers.py:432: in _reverse_with_prefix
    self._populate()
../../../Virtual/omero/lib/python2.7/site-packages/django/core/urlresolvers.py:307: in _populate
    for name in pattern.reverse_dict:
../../../Virtual/omero/lib/python2.7/site-packages/django/core/urlresolvers.py:337: in reverse_dict
    self._populate()
../../../Virtual/omero/lib/python2.7/site-packages/django/core/urlresolvers.py:325: in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
../../../Virtual/omero/lib/python2.7/site-packages/django/core/urlresolvers.py:246: in callback
    self._callback = get_callable(self._callback_str)
../../../Virtual/omero/lib/python2.7/site-packages/django/utils/lru_cache.py:101: in wrapper
    result = user_function(*args, **kwds)
../../../Virtual/omero/lib/python2.7/site-packages/django/core/urlresolvers.py:111: in get_callable
    if submod and not module_has_submodule(import_module(parentmod), submod):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

name = 'webgateway', package = None

    def import_module(name, package=None):
        """Import a module.
    
        The 'package' argument is required when performing a relative import. It
        specifies the package to use as the anchor point from which to resolve the
        relative import to an absolute import.
    
        """
        if name.startswith('.'):
            if not package:
                raise TypeError("relative imports require the 'package' argument")
            level = 0
            for character in name:
                if character != '.':
                    break
                level += 1
            name = _resolve_name(name[level:], package, level)
>       __import__(name)
E       ImportError: No module named webgateway
```

**Comment by joshmoore** [comment]
Perhaps django is importing relative to the settings? This is likely why there's this block in the old setup.py: https://github.com/ome/openmicroscopy/blob/develop/components/tools/OmeroWeb/setup.py#L27

cc: @ome/python

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#39](https://py3-ci.openmicroscopy.org/job/OMERO-python-superbuild-push/39/). See the [console output](https://py3-ci.openmicroscopy.org/job/OMERO-python-superbuild-push/39/consoleText) for more details.
Possible conflicts:
  - PR #3 will-moore 'table download'
    - test/integration/test_plategrid.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#41](https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/41/). See the [console output](https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/41/consoleText) for more details.
Possible conflicts:
  - PR #3 will-moore 'table download'
    - test/integration/test_plategrid.py

--conflicts

**Comment by will-moore** [comment]
This is failing travis because it's being tested with py3 (where ```1L``` is invalid).
It's now conflicting with #15.
When travis was last green, I don't see the tests being run in the log, so I don't know if they would pass/fail as above.
If some are still failing, perhaps we can disable/mark them and get the other fixes in? Or I could merge this branch into my #15 since they cover similar issues and this would avoid merge conflicts?

**Comment by joshmoore** [comment]
> This is failing travis because it's being tested with py3 (where 1L is invalid).

py2 seems to be failing, too.
```
ERROR:   py27: commands failed
ERROR:   py36: commands failed
```

Turning off py36 in this PR would definitely make sense. My bad. 

> Or I could merge this branch into my #15 since they cover similar issues and this would avoid merge conflicts?

I'd avoid this since it may be a while before we get the python 3 work merged into master.

**Comment by will-moore** [comment]
Created issue for the test_web tests marks with xfail: https://github.com/ome/omero-web/issues/18

**Comment by will-moore** [comment]
The ```''``` empty URLs were never handled by any views code, so I'm not sure what they did. I think they are some legacy way of defining URLs that's now been dropped.
Each component handles it's base URL with a regex like this one for webclient
```
url(r'^$', views.load_template, {'menu': 'userdata'}, name="webindex"),
```
and that is unchanged.
The new URL style shouldn't have any effect on users.

**Comment by joshmoore** [comment]
Great, thanks. Propose merging based on the outcome of https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/150/console and then I'll tag as `5.5.1`.

**Comment by will-moore** [comment]
E.g. https://merge-ci.openmicroscopy.org/web/webgateway/plate/4256/0/ (user-3) is failing with 
```
"Reverse for 'webgateway.views.render_thumbnail' with arguments '('64460',)' and keyword arguments '{}' not found. 0 pattern(s) tried: []"
```

**Comment by joshmoore** [comment]
As https://github.com/ome/omero-py/pull/19#issuecomment-535004150, changes here are green.

The changes here will need to be reviewed before this is released, but in order to have a single branch to work from, merging this as the basis for moving to 5.6.dev1 as discussed this morning.

https://github.com/ome/omero-web/issues/18 is likely still an issue.

**Comment by joshmoore** [comment]
Merging this PR led to a regression in ~30 tests: https://latest-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/126/

@will-moore will look into the total of PRs that are needed to consider this old style usage "buggy" behavior.

**Comment by will-moore** [comment]
28 of them will be fixed by merging https://github.com/ome/openmicroscopy/pull/6107
as happened on https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/155/
 and https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/156/ leaving one to fix in OmeroWeb.test.integration.test_csrf/TestCsrf/test_avatar/
```
>               im = Image.open(StringIO(photo.decode()))
E               UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 0: ordinal not in range(128)
```
I'll look at that now...

**Comment by joshmoore** [comment]
Ok, thanks. Merging 6107 as you look at the other required PRs to get everything green.  Added to the Python 3 board though so we can review how breaking the sum of the PRs are and take action if necessary.

**Pull request merged**
