### PR TITLE
Fix import basestring - batch annotate fix

### PR DESCRIPTION
**Pull request by will-moore**
Fix row 10 "Multiselect of any container in LHP does not work - just a blank "Send feedback" form comes up" from https://docs.google.com/spreadsheets/d/1ry6vS0dmsylFQDAiIZDrPC3kXNpnHSMtK-2yj5X8jaU/edit#gid=420881033

### CODE REVIEW

**Comment by joshmoore** [comment]
@will-moore : how does an import lead to the blank panel?

**Comment by will-moore** [comment]
The missing import caused a 500 error, triggering feedback dialog but because feedback is disabled on that server, the feedback dialog content didn't load.
________________________________

**Comment by joshmoore** [comment]
But the import is commented out.

**Comment by pwalczysko** [comment]
How could we get this deployed on py3-ci asap ?

**Comment by will-moore** [comment]
Ooops - sorry. I commented it out to check my test would catch it 🤒  - fixing...

**Comment by joshmoore** [comment]
Re-opening to see if that triggers travis status.

**Comment by joshmoore** [comment]
Looks good, thanks!

**Pull request merged**
