### PR TITLE
Update to Django 3.2.x

### PR DESCRIPTION
**Pull request by chris-allan**
## Introduction

This PR is a follow on from the Django 2.2.x upgrade WIP #200. The great initial work on that PR is unfortunately insufficient to bring us up to scratch with Django LTS versions; Django 2.2.x leaves LTS in just a few months in April 2022 [^1]. Django 3.2.x will remain in LTS until April 2024 [^2]:.

Furthermore, the strategy followed in this PR is slightly different: make the minimum number of changes required to maintain OMERO.web functionality and leave potential Django infrastructure modernisation to other follow up PRs.

Release notes for the major versions between our current 1.11.x and the 3.2.x target:

* https://docs.djangoproject.com/en/4.0/releases/2.0/
* https://docs.djangoproject.com/en/4.0/releases/2.1/
* https://docs.djangoproject.com/en/4.0/releases/2.2/
* https://docs.djangoproject.com/en/4.0/releases/3.0/
* https://docs.djangoproject.com/en/4.0/releases/3.1/
* https://docs.djangoproject.com/en/4.0/releases/3.2/

The `django-pipeline` dependency has been updated to nearly the latest version in order to support Django 3.2.x. All other dependencies have been left alone.

__NOTE:__ The supported Python versions for Django 3.2.x are currently 3.6, 3.7, 3.8, 3.9, and 3.10. This PR does not currently contain the requisite changes for Python 3.10 support.

## Proposed path to release

1. Decide on the new target version; I've selected 6.0.0 for the purposes of discussion
2. Release new versions of several OMERO.web plugins/applications with version pinning of `omero-web` to `<6.0.0`
3. Publicly announce that `omero-web` 6.0.0 __will__ include an upgrade to Django 3.2.x and publish the ideal timeline
4. Make whatever changes to this PR are required in order to have a test candidate; testing will need to be __extensive__ and __thorough__ as there's no telling what subtle bugs may be introduced
5. Deploy the test candidate and iterate until we are comfortable enough to publish a release candidate for community consumption
6. Continue to iterate, publishing new release candidates if required, until we are comfortable enough to make a release; this may include being comfortable with a subset of Django 3.2.x compliant OMERO.web plugins/applications
7. Make new releases of compliant OMERO.web plugins with version pinning of `omero-web` to `>=6.0.0`

### Django 2.0.x / 2.1.x

* `django.core.urlresolvers` removal (deprecated since 1.10) [^3]:
* Removal of case insensitive URL matching and simplified URL routing syntax (deprecated since 1.1.1) [^4][^5][^6]
* Small adjustments to the Server model to operate like a QuerySet due to changes in the form an choice APIs

### Django 3.0.x

* Use the new static templatetags package (deprecated since 2.1) [^7]:
* Updates to the new field ordering style for models [^8]:

### Django 3.1.x

* Update to the new internal settings cleansing API
* Use the new package for empty value definitions

### Django 3.2.x

[^1]: https://docs.djangoproject.com/en/4.0/releases/3.2/#django-3-2-release-notes
[^2]: https://www.djangoproject.com/download/#supported-versions
[^3]: https://docs.djangoproject.com/en/4.0/releases/1.10/#id3
[^4]: https://docs.djangoproject.com/en/4.0/releases/1.11/#id2
[^5]: https://docs.djangoproject.com/en/4.0/releases/2.0/#simplified-url-routing-syntax
[^6]: https://code.djangoproject.com/ticket/31099
[^7]: https://docs.djangoproject.com/en/4.0/releases/2.1/#id2
[^8]: https://docs.djangoproject.com/en/3.0/ref/forms/api/#notes-on-field-ordering

### CODE REVIEW

**Comment by chris-allan** [comment]
Current state is OMERO.web starts up and I have validated login, logout and a small amount of basic functionality.

**Comment by chris-allan** [comment]
All test cases now passing.

**Comment by jburel** [comment]
I have not updated Jenkins-ci to scl python 3.8. This PR will be included tomorrow. We will see how it goes and if some adjustments in the CI infra are needed too.

**Comment by chris-allan** [comment]
@jburel: Just a quick thought.: Does the current CI testing infrastructure include any OMERO.web plugins? OMERO.iviewer or OMERO.figure for example? If so, we might need to disable or remove them until we're happy with vanilla OMERO.web as there's a high chance it won't even start up if we don't have plugins updated to the new APIs.

**Comment by chris-allan** [comment]
List of potential plugins on the CI testing infrastructure from @will-moore on the other PR:

* https://github.com/ome/omero-web/pull/200#issuecomment-712117842

**Comment by jburel** [comment]
Plugins are included. i will turn them off.

**Comment by jburel** [comment]
Is there a specific version of ``django-cors-headers`` to have installed? It is currently pinned to ``3.2.1`` in merge-ci

**Comment by jburel** [comment]
I will pin to 3.7.0 on merge-ci and to the latest on new-ci for testing

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#3](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/3/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/3/consoleText) for more details.
Possible conflicts:
  - PR #336 will-moore 'Acquisition metadata json'
    - omeroweb/webclient/urls.py

--conflicts

**Comment by jburel** [comment]
--exclude

**Comment by chris-allan** [comment]
@jburel also noted that if `django-redis` is in use a compatible version of that is also required. At least version 5.0.0 of that dependency is needed:

* https://github.com/jazzband/django-redis/blob/master/CHANGELOG.rst#django-redis-500-2021-05-30

**Comment by sbesson** [comment]
Cross-linking to https://github.com/ome/omero-documentation/pull/2216#discussion_r808826511 for a wider question regarding the management of the non-minimal `django` dependencies.

**Comment by will-moore** [comment]
Excluding this PR from the build while we test upgraded apps with Django 1.11 as described in https://github.com/orgs/ome/projects/21#card-78410459

--exclude

**Comment by jburel** [comment]
See https://github.com/ome/omero-web/pull/359
* ``cors-header`` added as a dependency
* ``django-redis`` via ``extra`` option

In order for the GHA to pass, we need to first create an rc

Any more commits to be pushed?

**Comment by sbesson** [comment]
> In order for the GHA to pass, we need to first create an rc 

All for having a release candidate in general. But looking at the build failures, my expectation is that the issue is that there is some Django incompatibility in the package requirements in #357. Merging this and resovling the `setup.py` conflicts as needed might be sufficient to turn the builds green.

**Comment by jburel** [comment]
Sorry I was referring to the GHA of mapr see https://github.com/ome/omero-mapr/runs/5302759242?check_suite_focus=true

**Comment by sbesson** [comment]
:+1: For downstream apps, I also expect pre-releases will fix the coupling issues (and also allow to express the dependency requirements)

**Comment by chris-allan** [comment]
> Any more commits to be pushed?

None that I know of with respect to compatibility with Django 3.2.x

Would you like me to include the contents of #359 here? Would that help with your build failures?

**Comment by jburel** [comment]
i will merge this PR and restart the GHA.
That should work

Thanks all

**Pull request merged**
