### PR TITLE
Right panel performance fixes

### PR DESCRIPTION
**Pull request by will-moore**
Port PR from https://github.com/ome/openmicroscopy/pull/6075/

This PR contains 2 approaches to improve right panel performance:
 - tries to reduce the times that `conn.getExperimenter()` is called for right panel - e.g. single P/D/I etc (see link above)
 - improves loading speed of batch-annotate panel (when multiple objects selected) by NOT loading the toolbar download menu until the user clicks on it. This was being very slow when many Images are selected (as in https://github.com/ome/omero-web/pull/225) because the 'canDownloadAsJpg()` to enable png/tiff/jpeg download was calling 'image.getSizeX()` etc for every image (loading the pixels on the fly each time). To test, select multiple objects and test behaviour of the Download menu.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#16](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/16/). See the [console output](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/16/consoleText) for more details.
Possible conflicts:
  - PR #3 will-moore 'table download'
    - omeroweb/webclient/views.py
  - PR #15 will-moore 'Py3 fixes'
    - omeroweb/webclient/views.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#17](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/17/). See the [console output](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/17/consoleText) for more details.
Possible conflicts:
  - PR #3 will-moore 'table download'
    - omeroweb/webclient/views.py
  - PR #15 will-moore 'Py3 fixes'
    - omeroweb/webclient/views.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#22](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/22/). See the [console output](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/22/consoleText) for more details.
Possible conflicts:
  - PR #3 will-moore 'table download'
    - omeroweb/webclient/views.py
  - PR #15 will-moore 'Py3 fixes'
    - omeroweb/webclient/views.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#14](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-python-superbuild-push/14/). See the [console output](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-python-superbuild-push/14/consoleText) for more details.
Possible conflicts:
  - PR #3 will-moore 'table download'
    - omeroweb/webclient/views.py
  - PR #15 will-moore 'Py3 fixes'
    - omeroweb/webclient/views.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#59](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/59/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/59/consoleText) for more details.
Possible conflicts:
  - PR #3 will-moore 'table download'
    - omeroweb/webclient/views.py
  - PR #15 will-moore 'Py3 fixes'
    - omeroweb/webclient/views.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#25](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/25/). See the [console output](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/25/consoleText) for more details.
Possible conflicts:
  - PR #3 will-moore 'table download'
    - omeroweb/webclient/views.py
  - PR #15 will-moore 'Py3 fixes'
    - omeroweb/webclient/views.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#15](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-python-superbuild-push/15/). See the [console output](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-python-superbuild-push/15/consoleText) for more details.
Possible conflicts:
  - PR #3 will-moore 'table download'
    - omeroweb/webclient/views.py
  - PR #15 will-moore 'Py3 fixes'
    - omeroweb/webclient/views.py

--conflicts

**Comment by jburel** [comment]
Excluding ahead of the dependencies upgrade work
--exclude

**Comment by will-moore** [comment]
Need to create a lot of users on merge-ci to test. Created a group called `many_users`, then...

```
$ for i in {1..200}; do omero user add test-$i name-$i surname-$i many_users -P ome --ignore-existing; done
```

**Comment by will-moore** [comment]
Removed "exclude" flag 9th Feb

**Comment by will-moore** [comment]
Going to exclude from build temporarily, so we can check performance on merge-ci on groups with few or many users...

--exclude

**Pull request closed without merging**
