### PR TITLE
copy/paste right_plugin.general.js.html instead of include it

### PR DESCRIPTION
**Pull request by will-moore**
Trying to fix https://github.com/ome/omero-web/pull/50#issuecomment-549707554
which is only seen on merge-ci (works fine locally and on py3-ci).

### CODE REVIEW

**Comment by joshmoore** [comment]
Tag creation _does_ work today on merge-ci/web. Does that point to a solution that doesn't require the TEMP copying of the script?

**Comment by will-moore** [comment]
I still don't know why the ```include``` failed before on merge-ci, but it has nothing to do with the tagging fix in https://github.com/ome/omero-web/pull/50/.

**Comment by will-moore** [comment]
As discussed, since the include is only used in one place (apart from old unused front page) we don't need to duplicate code if we simply in-line the include code (as committed above).
So can clean-up for merge...

**Comment by will-moore** [comment]
Update - As Simon suggested, this is likely due to mapr right panel not loading (it overwrites the included template). This would explain why this is failing on merge-ci but not locally or on py3-ci.
Also, it highlights that in-lining the include as suggested above, would break mapr!
Closing...

**Comment by will-moore** [comment]
Just confirmed that merge-ci (python 2.7 and Django 1.11) can't run the current release of mapr. Fails with:

```
File "/Users/willadmin/Desktop/WEB/omero-web/omeroweb/urls.py", line 85, in <module>
    __import__(urlmodule)
  File "/Users/willadmin/Desktop/MAPR/omero-mapr/omero_mapr/urls.py", line 23, in <module>
    from . import views
  File "/Users/willadmin/Desktop/MAPR/omero-mapr/omero_mapr/views.py", line 62, in <module>
    from omeroweb.http import HttpJPEGResponse
ImportError: No module named http
```

But, since mapr is installed there, the mapr right_plugin template overwrites the webclient one, but fails to render (imports fail etc) so we get no right panel.
This is fixed in https://github.com/ome/omero-mapr/pull/54

**Pull request closed without merging**
