### PR TITLE
gateway: view

### PR DESCRIPTION
**Pull request by jburel**
* Use parent from link
* fix remaining flake8 warning

This should hopefully fix
https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/43/testReport/junit/OmeroWeb.test.integration.test_plategrid/TestScreenPlateTables/test_get_plate_table/

### CODE REVIEW

**Comment by will-moore** [comment]
Should also fix https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/44/testReport/OmeroWeb.test.integration.test_metadata/TestBulkAnnotations/test_nsbulkannotations_file_True_/

```
                                                   File "/Users/willadmin/Desktop/WEB/omero-web/omeroweb/webgateway/views.py", line 1356, in wrap
                                                     rv = f(request, *args, **kwargs)
                                                   File "/Users/willadmin/Desktop/WEB/omero-web/omeroweb/webgateway/views.py", line 2775, in _bulk_file_annotations
                                                     parentId=obj.id.val,
                                                 NameError: name 'obj' is not defined
```

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#144](https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/144/). See the [console output](https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/144/consoleText) for more details.
Possible conflicts:
  - PR #3 will-moore 'table download'
    - omeroweb/webgateway/views.py
  - Upstream changes
    - omeroweb/webgateway/views.py

--conflicts

**Comment by will-moore** [comment]
I'll close my PR #3 to let this one get in first...

**Comment by jburel** [comment]
https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/46/testReport/OmeroWeb.test.integration.test_metadata/TestBulkAnnotations/test_nsbulkannotations_file_True_/ is fixed

**Comment by joshmoore** [comment]
https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/46/testReport/junit/OmeroWeb.test.integration.test_plategrid/TestScreenPlateTables/test_get_plate_table/ from the description is still failing.

**Comment by jburel** [comment]
Failure is related to another problem. This PR fixes the first issue and hopefully the test will be green next build

**Comment by will-moore** [comment]
https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/47/testReport/junit/OmeroWeb.test.integration.test_plategrid/TestScreenPlateTables/test_get_plate_table/
and
https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/47/testReport/OmeroWeb.test.integration.test_metadata/TestBulkAnnotations/test_nsbulkannotations_file_True_/
now passing.

Once this is merged, I can re-open my tables PRs and fix conflicts etc.

**Comment by joshmoore** [comment]
merge (230) and py3 (49) are still green. :+1:

**Pull request merged**
