### PR TITLE
Test proposed scripts button changes

### PR DESCRIPTION
**Pull request by will-moore**
I was just trying out some suggestions from https://forum.image.sc/t/mini-ui-edits-for-maxi-ux-benefits/87821 and thought I'd open a PR just to save them (and give others a chance to try)...

Before:
Screenshot 2023-10-25 at 12 01 06

After:
Screenshot 2023-10-25 at 12 01 23

### CODE REVIEW

**Comment by will-moore** [comment]
cc @knabar - What do you think of this change?
@jburel and @pwalczysko are in favour of making these buttons configurable and not to change the default behaviour. I agree that this would minimise the impact: no changes needed for omero-guides etc and this includes Glencoe.
But, I think this change looks like an improvement and configuration should only be used if different users *need* different UIs, since it has a cost for us to implement/test and users to configure.

**Comment by knabar** [comment]
@will-moore My initial thought is that the easiest would be to utilize CSS to have users who want to do so change the buttons.

For example, by adding the following CSS, you can change the button from having an icon to having text, without needing to add configuration settings or changing the behavior for everybody:

```css
#scriptButton::before {
    content: 'Scripts';
    line-height: 23px;
    color: lightgrey;
    font-size: larger;
    padding: 5px;
}
#scriptButton {
    background: none;
}
```

Getting the CSS onto the page would (I think) currently require overriding a template, but we have that process already.

**Comment by will-moore** [comment]
@knabar "easiest" for us, since we do nothing! But not so easy for users. Do we have any docs for overriding a template (other than the Django docs themselves)?

My feeling is that I agree with https://forum.image.sc/t/mini-ui-edits-for-maxi-ux-benefits/87821 that this is actually an improvement for all users, so we should just make the change for everyone.

**Review by pwalczysko — CHANGES_REQUESTED** [review]
LGTM on merge-ci. But the discussion here is obviously important with regards to the customization strategies. Can I ask whether the discussion has crystalized with respect to this very PR ?

**Comment by will-moore** [comment]
I think the consensus is to not change this for everyone as proposed in this PR but instead to improve the customisation workflow and docs.
I'll close this now...

**Pull request closed without merging**
