### PR TITLE
Pre commit hook

### LINKED ISSUE #208: pre-commit hooks for flake8
As discussed in https://openmicroscopy.slack.com/archives/C0K5EED3R/p1598024734064600
it would be nice to set up pre-commit hooks to do flake8 checks etc before pushing, to avoid repeated Travis failures on this repo and others.

This has already happened for https://github.com/ome/ome-zarr-py/blob/master/.pre-commit-config.yaml

cc @manics 

With `pre-commit==2.6.0` installed I did

```
$ pre-commit run -a
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

test/unit/test_util.py:71:9: E123 closing bracket does not match indentation of opening bracket's line
test/unit/test_util.py:79:9: E123 closing bracket does not match indentation of opening bracket's line
omeroweb/webgateway/views.py:262:31: E226 missing whitespace around arithmetic operator
omeroweb/webgateway/views.py:262:35: E226 missing whitespace around arithmetic operator
...
omeroweb/webclient/controller/container.py:542:51: E226 missing whitespace around arithmetic operator
omeroweb/webclient/controller/container.py:597:51: E226 missing whitespace around arithmetic operator
omeroweb/webclient/controller/container.py:639:51: E226 missing whitespace around arithmetic operator
omeroweb/webclient/controller/container.py:687:53: E226 missing whitespace around arithmetic operator
omeroweb/webclient/controller/container.py:793:50: W504 line break after binary operator
test/unit/test_render_response.py:92:9: E123 closing bracket does not match indentation of opening bracket's line

yamllint.................................................................Failed
- hook id: yamllint
- exit code: 1

.pre-commit-config.yaml
  17:9      warning  comment not indented like content  (comments-indentation)

.travis.yml
  14:81     error    line too long (137 > 80 characters)  (line-length)
  30:3      warning  truthy value should be one of [false, true]  (truthy)
```

This found many flake8 issues, although my local `flake8` passes.

Having introduced a deliberate local flake8 failure:
```
$ flake8
./omeroweb/webclient/views.py:114:1: E302 expected 2 blank lines, found 1
```

I was still able to commit and push this to https://github.com/ome/omero-web/pull/207

### PR DESCRIPTION
**Pull request by will-moore**
Adding pre-commit flake8 checking.
Fixes #208

### CODE REVIEW

**Comment by manics** [comment]
FYI this is what it looks like with black enabled:
https://github.com/ome/omero-web/commit/10f06339d0f7ccca52ad00be6e030e2beae14ffe

**Comment by manics** [comment]
Can you change tox to run pre-commit instead of flake8 directly? https://github.com/ome/omero-web/blob/d877249b120c5414cf07e45eb43cc0c9ca187d06/tox.ini#L31 Otherwise there could be conflicts between the two separate flake8 configurations

**Comment by will-moore** [comment]
Done. But I'm not sure I understand how that would help since tox doesn't get run before each commit?
Or does it just need running once to set-up the pre-commit hook?

Ooops - I noticed that the PR branch is `origin/pre-commit-hook` instead of `will-moore/pre-commit-hook`. Must have accidentally pushed to wrong place.

**Comment by will-moore** [comment]
Trying to run `tox`:

```
$ tox
GLOB sdist-make: /Users/wmoore/Desktop/WEB/omero-web/setup.py
py36 create: /Users/wmoore/Desktop/WEB/omero-web/.tox/py36
ERROR: InterpreterNotFound: /opt/rh/rh-python36/root/usr/bin/python3.6
____________________________________________________________________________________ summary _____________________________________________________________________________________
ERROR:  py36: InterpreterNotFound: /opt/rh/rh-python36/root/usr/bin/python3.6
(omeroweb) LS30778:omero-web wmoore$ which python
/Users/wmoore/opt/miniconda3/envs/omeroweb/bin/python
(omeroweb) LS30778:omero-web wmoore$ python --version
Python 3.6.10 :: Anaconda, Inc.
```

**Comment by will-moore** [comment]
Re: https://github.com/ome/omero-web/pull/207#issuecomment-682076005
I would love enable Black locally to run on Save.
Would save so much time formatting etc.
So we should just pick a time and commit all the changes needed.

**Comment by joshmoore** [comment]
The pre-commit configure works for me, though I get many more errors, almost 400:

```
(z) /opt/omero-web $pre-commit run -a | sed 's/.*[.]py.*/python files/' | uniq -c
   1 flake8...................................................................Failed
   1 - hook id: flake8
   1 - exit code: 1
   1
 381 python files
   1
   1 yamllint.................................................................Failed
   1 - hook id: yamllint
   1 - exit code: 1
   1
   1 .pre-commit-config.yaml
   1   17:9      warning  comment not indented like content  (comments-indentation)
   1
   1 .travis.yml
   1   14:81     error    line too long (137 > 80 characters)  (line-length)
   1   30:3      warning  truthy value should be one of [false, true]  (truthy)
   1
```

Perhaps related to your local versions? (I'm using the conda environment created from the ome-zarr-py repository).

The travis job is failing on tox because it's not a git repository:

```
py36 run-test: commands[0] | pre-commit run --all-files
2007An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
2008Check the log at /home/tox/.cache/pre-commit/pre-commit.log
```

I've pushed a commit to fix that, but there may be other options so that we could roll it back.

NB:
```
INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    error: RPC failed; result=22, HTTP code = 404
    fatal: The remote end hung up unexpectedly
```
looks like a type of flakiness that we may have to deal with.

**Comment by manics** [comment]
It might be easier if we just go ahead with black instead of dealing with flake8 versions....

In this repo PRs are open by
- myself (I'm happy to fix/rebase my PRs after black is added)
- @stick (the Python change is only a one-line comment so easy to fix https://github.com/ome/omero-web/pull/168/files#diff-fd8b729f3409e169aadb500358d1b53cR164)
- @will-moore 

Thoughts?

**Comment by will-moore** [comment]
I would like to aim for black. I have a bunch of PRs, hopefully most of them will soon be merged into 5.8.0 release: https://github.com/ome/omero-web/milestone/2
Then I could try merging master back into my other PRs before applying black to master and to those branches.
Hopefully they should still be mergeable then.

**Comment by will-moore** [comment]
I get this:

```
$ pre-commit run -a | sed 's/.*[.]py.*/python files/' | uniq -c
   1 flake8...................................................................Failed
   1 - hook id: flake8
   1 - exit code: 1
   1 
 381 python files
   1 
   1 yamllint.................................................................Failed
   1 - hook id: yamllint
   1 - exit code: 1
   1 
   1 .pre-commit-config.yaml
   1   17:9      warning  comment not indented like content  (comments-indentation)
   1 
   1 .travis.yml
   1   14:81     error    line too long (137 > 80 characters)  (line-length)
   1   30:3      warning  truthy value should be one of [false, true]  (truthy)
   1 
```

But I thought the whole point of pre-commit hooks was that they ran automatically when you try to commit (and prevent you from committing flake8 failures)? But that's not working for me yet.

**Comment by joshmoore** [comment]
> But I thought the whole point of pre-commit hooks was that they ran automatically when you try to commit (and prevent you from committing flake8 failures)? But that's not working for me yet.

Have you run `pre-commit install` in this repository? see https://pre-commit.com/#3-install-the-git-hook-scripts

**Comment by manics** [comment]
https://github.com/will-moore/omero-web/pull/2 adds the black config but does not reformat everything so it should be OK to merge it. We can then run `pre-commit run -a` and commit the result when it's convenient

**Comment by will-moore** [comment]
Ah, yes - that works!
```
$ pre-commit install
pre-commit installed at .git/hooks/pre-commit
```
Now I probably need to disable it again since it's finding too many flake8 issues and I don't want to fix them all manually.
Let's try to shoot for `black` instead when ready.

**Comment by manics** [comment]
See https://github.com/ome/omero-web/pull/218 (draft/excluded) for an updated version of this PR

**Pull request closed without merging**
