### PR TITLE
Fix display of stdout, stderr script results

### PR DESCRIPTION
**Pull request by will-moore**
Fixes a bug noticed in manual testing of scripts in webclient where results and stdout, stderr buttons were not showing:

To test: run a script that returns something and check that this is shown in the Activities dialog.

Screen Shot 2019-11-08 at 11 28 36

I'll add a test to catch this.

### CODE REVIEW

**Comment by joshmoore** [comment]
_ewww_ Did the error produce a warning that we could detect? Can we flake8 within html?!

**Comment by will-moore** [comment]
Travis failed with:

test/unit/test_webgateway.py ⨯✓✓✓✓

```
>       assert self.wcache.getThumb(self.request, 'test', uid, 0) is None, (
            'Time limit failed')
E       AssertionError: Time limit failed
```
I don't think this is related to this PR?

**Comment by joshmoore** [comment]
Re-opening to trigger travis

**Comment by joshmoore** [comment]
Last commit is now green on travis, but it's not showing up here.

**Comment by will-moore** [comment]
The test added to test this fix is now failing as expected with this PR excluded due to travis:

https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/53/testReport/OmeroWeb.test.integration.test_scripts/TestScripts/test_script_inputs_outputs_inputs0_/

**Comment by joshmoore** [comment]
Trying to re-open

**Comment by will-moore** [comment]
As discussed, https://github.com/will-moore/scripts/commit/802fb33df77cb1972abe4d788ad97f176fa8bda1 is not on this PR but is displayed above as if it is. Travis now green for the single commit.

**Comment by joshmoore** [comment]
This PR was included:

```
Merged PRs:
...
  - PR 61 will-moore 'Fix display of stdout, stderr script results'
```

but https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/lastCompletedBuild/testReport/OmeroWeb.test.integration.test_scripts/TestScripts/test_script_inputs_outputs_inputs0_/ and https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/54/testReport/ still failed.

**Comment by will-moore** [comment]
My test actually exposed a bug (the activities dialog assumed that there was only 1 result). Should be fixed by that last commit.

**Comment by will-moore** [comment]
Fixed at https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/55/testReport/OmeroWeb.test.integration.test_scripts/TestScripts/test_script_inputs_outputs_inputs0_/ and
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/236/testReport/junit/OmeroWeb.test.integration.test_scripts/TestScripts/test_script_inputs_outputs_inputs0_/

**Comment by joshmoore** [comment]
The listed tests definitely passed. It's a bit odd that https://latest-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/179/testReport/OmeroWeb.test.integration.test_scripts/TestScripts/test_script_inputs_outputs_inputs0_/ is passing, _too_, though. I assume that's because https://github.com/ome/openmicroscopy/pull/6173isn't merged?

This is a significantly long diff that I've listed for a code review.

**Comment by joshmoore** [comment]
Testing after an explanation from @will-moore:

> (paraphrased) Previously the code was assuming only one image and/or one file annotation and nothing else. The test added in 6173 returned multiple and not necessarily one of the above as the first, leading to issues.

I copied the test from 6173 to py3-ci and successfully ran:

Screen Shot 2019-11-14 at 12 03 09

:+1:  A limitation likely for another a follow-up is that only one of the images that was specified is viewable, i.e. the eye icon links to `https://py3-ci.openmicroscopy.org/web/webclient/userdata/?show=image-851#` rather than something with multiple images. I assume the same would happen for multiple FileAnnotations.

**Comment by will-moore** [comment]
@joshmoore Yes, we only support a single "Image" key output, same for "FileAnnotation". Could certainly make this more flexible in future if needed.

**Comment by joshmoore** [comment]
:+1: Leaving that to you, and merging the two PRs.

**Pull request merged**
