### PR TITLE
Fix feedback url encode

### LINKED ISSUE #129: Feedback form doesn't work
1. From the user menu go to `Send Feedback` (`http://omero.example.org/feedback/comment/`)
2. Attempt to send some feedback. It fails with `Feedback could not be sent. Please contact administrator.`
3. `OMEROweb.log` contains:
```
2020-02-17 13:24:29,204 ERROR [                 omeroweb.feedback.views] (proc.12416) send_feedback():78 Traceback (most recent call last):
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/feedback/sendfeedback.py", line 90, in send_feedback
    data = urllib.urlencode(p)
AttributeError: module 'urllib' has no attribute 'urlencode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/feedback/views.py", line 75, in send_feedback
    user_agent=get_user_agent(request))
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/feedback/sendfeedback.py", line 119, in send_feedback
    raise Exception("Feedback server error: %s" % x.message)
AttributeError: 'AttributeError' object has no attribute 'message'
```

### PR DESCRIPTION
**Pull request by will-moore**
Fixes #129 

To test, try sending feedback error.
See #132 for details on how to do that.

Feedback should work - if you include e-mail address you should get e-mail and QA will be created etc.

### CODE REVIEW

**Comment by jburel** [comment]
Cannot send feedback using merge-ci

**Comment by will-moore** [comment]
Merge-ci OMERO-web job currently has settings:

```
# QA feedback configuration
omero config set omero.web.feedback.comment.enabled false
omero config set omero.web.feedback.error.enabled false
```

Not sure why these got set, but seems wrong for testing server.
I'll remove...

**Comment by jburel** [comment]
https://www.openmicroscopy.org/qa2/qa/feedback/29079/ created

**Comment by joshmoore** [comment]
> Not sure why these got set, but seems wrong for testing server.
> I'll remove...

IIRC at some point we were getting quite a lot of false positives during testing. I'm all for having it on, but we may have to see how it pans out. An alternative would be to run a secondary QA just for these, but better is likely to have the error handling such that new feedback items are minimized.

**Pull request merged**
